services:
  catalogdb:
    image: postgres
    volumes:
      - postgres_catalog:/var/lib/postgresql/data 

  distributedcache:
    image: redis

  basketdb:
    image: postgres
    volumes:
      - postgres_basket:/var/lib/postgresql/data  
volumes:
  postgres_catalog:
  postgres_basket:

