
version: '3.9'

services:

  catalogdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalogDb
    ports:
      - 5432:5432
  basketdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BasketDb
    ports:
      - 5433:5432

  distributedcache: 
     container_name: distributedcache
     restart: always
     ports: 
     - "6379:6379"

